In [2]:
# Supporting libraries
import os
from dotenv import load_dotenv
import time
#dotenv
from openai import OpenAI
from PyPDF2 import PdfReader 
import pandas as pd
import os
from pathlib import Path

C:\Users\Buket Fildisi\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
openai_api_key=""
os.environ["OPENAI_API_KEY"] = openai_api_key

In [6]:
# Extract full text
import pdfplumber
import nltk
nltk.download("punkt")
pdf_text = ""
with pdfplumber.open("C:/Users/Buket Fildisi/Desktop/PhD/LLM/SDR__Implementation_Update_2024.pdf") as pdf:
    for page in pdf.pages:
        pdf_text += page.extract_text() + "\n"

# Split into sentences
sentences = nltk.sent_tokenize(pdf_text)
sentences

[nltk_data] Downloading package punkt to C:\Users\Buket
[nltk_data]     Fildisi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

['Sustainability Disclosure\nRequirements: Implementation\nUpdate 2024\nIntroduction - Sustainability Disclosure Requirements\n1.1 Mobilising Green Investment: 2023 Green Finance Strategy (2023) set out\nthe UK Government’s long-term strategy to ensure investors and consumers can\naccess the information they need to inform capital allocation in line with their\nsustainability preferences or goals.1 Central to this strategy is our plan for economy\nwide Sustainability Disclosure Requirements (SDR), as first set out in Greening\nFinance: A Roadmap to Sustainable Investing (2021).2 Building on global best\npractice and leading standards, SDR is a framework to facilitate and streamline the\nflow of robust, decision useful information between corporates, consumers and\ninvestors and capital markets.',
 '1.2 Financial markets are global, and international interoperability is a key\nprinciple of the UK’s approach to SDR.',
 'The 2023 Green Finance Strategy contained\na commitment to provide an SDR implementation update to reflect the rapid\ndevelopment of international standards.',
 'Following last year’s launch of the\nInternational Financial Reporting Standards (IFRS) Foundation’s International\nSustainability Standards Board (ISSB) baseline standards, this document provides\nthat update, setting out next steps on SDR and how industry can engage with the\ndevelopment of the different components.3\nComponents of SDR\nIFRS Sustainability Disclosure Standards\n1.3 The Government congratulated the ISSB on the publication of its inaugural\nstandards on 26 June 2023.',
 'The 2023 Green Finance Strategy explained that the\nGovernment is setting up an endorsement and implementation process for those\nstandards.',
 'The Government has today published a framework document which\nsets out further detail about that process and the advisory committees that will be\nsupporting the Government in taking this work forward.',
 'Please consult the\nframework document for further detail, including detail regarding the\nindependent UK Sustainability Disclosure Technical Advisory Committee that is\nbeing established to provide advice to the Secretary of State for Business and Trade\nwhen making an endorsement decision.4\n1.4 The Government aims to make the UK-endorsed ISSB standards\navailable in Q1 2025.',
 'The endorsement process will assess the standards and,\nsubject to a positive endorsement decision, will conclude with the publication of\n1 Mobilising Green Investment - 2023 Green Finance Strategy\n2 Greening Finance: A Roadmap to Sustainable Investing\n3 IFRS - IFRS Sustainability Standards Navigator\n4 Framework for Developing UK Sustainability Reporting Standards\nUK-endorsed standards.',
 'These will be known as UK Sustainability Reporting\nStandards.',
 '1.5 Subject to a positive endorsement decision by the UK Government, and\nfollowing a consultation process, the Financial Conduct Authority (FCA) will be\nable to use the UK Sustainability Reporting Standards to introduce\nrequirements for UK-listed companies to report sustainability-related\ninformation.',
 '1.6 Subject to a positive endorsement decision, the Government will also\ndecide on disclosure requirements against UK Sustainability Reporting\nStandards for UK companies that do not fall within the FCA’s regulatory\nperimeter.',
 'That decision will take into account a number of factors, including costs\nfor reporting companies and benefits for investors that may wish to use this\ninformation.',
 '1.7 The Government expects a decision regarding future requirements to be\ntaken in Q2 2025.',
 'At that time, the Government will also consider whether to\ncreate exemptions from pre-existing requirements in the Companies Act 2006 for\nthose companies that choose to use the standards on a voluntary basis.',
 'Any\ndecision that the Government takes on these matters will involve consultation and\nwill require Parliamentary approval for the introduction of any new legislation.',
 'As\na result, any changes that may be introduced would be effective no earlier than\naccounting periods beginning on or after 1 January 2026.',
 'Transition Plan Disclosures\n1.8 In April 2022, the Government launched the Transition Plan Taskforce (TPT)\nto develop a framework to help companies communicate their plan to achieve net\nzero to shareholders and other stakeholders.',
 '1.9 The Government, which co-chairs the TPT, is grateful for its important work,\nincluding the publication of their voluntary Disclosure Framework in October\n2023.5 The TPT’s Disclosure Framework has been designed purposefully to\nintegrate with and build from the approach to transition plans found in both the\nUK regulations6 and FCA rules7 that implement the Task Force on Climate-related\nFinancial Disclosures (TCFD) recommendations8 as well as the ISSB Standards and\nguidance from the Glasgow Financial Alliance for Net Zero (GFANZ) on transition\nplans.',
 '1.10 The ISSB’s climate-related disclosure standard, IFRS S2, includes a\nrequirement for companies to disclose details about their transition plan, if they\n5 The TPT Disclosure Framework | Transition Plan Taskforce\n6 Guidance on Climate-related financial disclosures for companies and limited liability partnerships\n7 FCA rules on TCFD-aligned reporting requirements\n8 TCFD recommendations\nhave one, and contains many disclosure requirements that are relevant to\ntransition planning.',
 'The TPT Disclosure Framework provides more detailed\nrecommendations on how to disclose effectively in line with these requirements.',
 '1.11 Given the overlap between IFRS S2 and the TPT Disclosure Framework, the\nFCA plans, through its consultation on implementing UK-endorsed ISSB\nstandards, to consult on strengthening its expectations for transition plan\ndisclosures with reference to the TPT Disclosure Framework.',
 '1.12 Given the important role of transition planning across the economy, the\nGovernment will consult shortly on how the UK’s largest companies can most\neffectively disclose their transition plans, meeting a key commitment of last\nyear’s Green Finance Strategy.',
 'SDR & Investment Labels\n1.13 The FCA finalised its Sustainability Disclosure Requirements (SDR) and\ninvestment labels regime for funds based in the UK, with the release of its policy\nstatement on 28 November 2023.9 The FCA engaged extensively with industry,\nincluding through their Disclosures and Labels Advisory Group, and carried out\nconsumer research to support the development of proposals and finalising the\nrules.',
 '10\n1.14 The package of measures includes investment labels, naming and\nmarketing rules, an anti-greenwashing rule for all FCA-authorised firms, and\ndisclosure rules.',
 'The anti-greenwashing rule comes into effect on 31 May 2024 and\nother parts of the regime will be phased in.',
 'Firms will be able to use labels from 31\nJuly 2024, and naming and marketing requirements must be met by 2 December\n2024, with further disclosure requirements phased in over the next two years.',
 '1.15 In April 2024, the FCA published a consultation on extending the SDR\nand labelling regime to portfolio managers based in the UK, which is open until\n14 June 2024.',
 'The FCA also finalised its guidance on the anti-greenwashing rule,\nfollowing a consultation which closed in January 2024.',
 '1.16 In January 2024, the Government announced that it intends to consult\non whether to broaden the scope of SDR to include funds under the Overseas\nFunds Regime.',
 'The Government intends to issue this consultation in Q3 2024.',
 'UK Green Taxonomy\n1.17 The Government reiterated its commitment in the 2023 Green Finance\nStrategy to delivering a UK Green Taxonomy to help mobilise investment into\ngreen activities and tackle greenwashing.',
 'Developing a usable and useful\n9 PS23/16: Sustainability Disclosure Requirements (SDR) and investment labels | FCA\n10 DLAG Terms of Reference\ntaxonomy is a complex and technical exercise.',
 'The Government continues to\nwork at pace and expects to consult in due course on the proposed UK Green\nTaxonomy, seeking feedback on both the overarching framework and use cases,\nas well as the specific activity level criteria which defines green activities.',
 '1.18 After the Taxonomy has been finalised following consultation feedback, the\nGovernment will introduce a testing period for voluntary disclosures and use for at\nleast two reporting years before exploring mandating disclosures.',
 'The Government\nhas not yet made a decision on whether to introduce mandatory disclosures\nagainst the Taxonomy.',
 'Any decision on this would be subject to further\nconsultation and would take account of the evidence from the initial voluntary\nphase of reporting to ensure that any potential reporting against a future\nTaxonomy provides accessible and reliable information that is useful to markets.',
 'Nature-Related Disclosures\n1.19 The Government welcomes initiatives such as the Taskforce on Nature-\nrelated Financial Disclosures (TNFD) which can help businesses and financial\ninstitutions assess and address their nature-related dependencies, impacts, risks,\nand opportunities.',
 'The Government congratulated the TNFD on the publication of\nits final recommendations, which launched at the New York Stock Exchange in\nSeptember 2023.',
 'The Government encourages institutions to engage in the TNFD\nUK National Consultation Group and consider the recommendations.',
 '1.20 The Government has followed with interest the ISSB’s Consultation on\nAgenda Priorities which recognises the importance of biodiversity, ecosystems,\necosystem services and human capital.',
 'It also notes the ISSB’s recent\nannouncement to commence research projects concerned with risk disclosure\nand opportunities associated with these issues, as part of an enhanced global\nbaseline of investor-focused sustainability disclosure.11 The Government continues\nto welcome the ongoing commitment of the ISSB to research and develop future\nadditional standards, which could also include reporting on nature-related risks\nand opportunities and encourages the ISSB to take the work and the holistic\nnature risk management approach of the TNFD into account at the appropriate\ntime.',
 '11 IFRS - ISSB to commence research projects about risks and opportunities related to nature and\nhuman capital\nFigure 1 – Timeline for SDR Implementation\nSDR Element Organisation 2024 2025\nQ2\n- Assessment of IFRS S1\nand IFRS S2 by the UK\nSustainability\nDisclosure Technical\nTechnical Advisory Committee\nAdvisory commences.',
 'Committee12\nQ4\n- Assessment concludes\nand recommendations\nprovided to the\nSecretary of State for\nBusiness and Trade.',
 'Q1\n- Consultation on draft\nUK Sustainability\nReporting Standards\nIFRS\n- Endorsement decision\nSustainability\nand publication of UK\nDisclosure Sustainability\nStandards - Disclosure Standards,\nEndorsement & subject to a positive\nImplementation endorsement decision.',
 'of UK-endorsed UK\nISSB standards Government\nQ2\n- Subject to a positive\nendorsement decision,\nthe Government will\nconsult on disclosure\nrequirements against\nthe UK Sustainability\nReporting Standards for\nUK companies that do\nnot fall within the FCA’s\nregulatory perimeter.',
 '- Support progress - Subject to\ntowards adopting ISSB- endorsement process,\nbased sustainability consultation on\nFCA disclosures for listed updating TCFD-aligned\ncompanies.',
 'rules to UK\nSustainability Reporting\nStandards.',
 '12 UK Sustainability Disclosure Standards - GOV.UK (www.gov.uk)\nQ2\n- Consultation on the\nGovernment approach\nUK\nto transition plan\nGovernment\ndisclosures for UK\ncompanies.',
 '- Subject to\nTransition Plan\nendorsement process,\ndisclosure\nconsultation on\nstrengthening\ntransition plan\nFCA\ndisclosure expectations\nin line with TPT\nframework.',
 '- Consultation on - Subject to consultation\nwhether to broaden the outcomes, legislation\nscope of SDR to include required to implement\nUK\nfunds recognised under SDR and labelling for\nGovernment\nthe Overseas Funds OFR funds is likely to be\nRegime.',
 'published.',
 '- Staggered - Continued\nSDR & implementation of final implementation of final\nInvestment rules.',
 'rules.',
 'Labels - Consultation on\n- Subject to the\nextending the regime\noutcomes of the\nto portfolio managers\nGovernment’s\nFCA\nand final rules.',
 'consultation, FCA will\n- Final anti-\nfollow a separate\ngreenwashing\nprocess to consult and\nguidance.',
 'make rules for overseas\nfunds.',
 '- Launch of consultation\nUK Green UK\non the design of the UK\nTaxonomy Government\nGreen Taxonomy.',
 '© Crown copyright 2023\nThis publication is licensed under the terms of the Open Government\nLicence v3.0 except where otherwise stated.',
 'To view this licence, visit\nnationalarchives.gov.uk/doc/open-government-licence/version/3.',
 'Where we have identified any third party copyright information you\nwill need to obtain permission from the copyright holders concerned.',
 'This publication is available at: www.gov.uk/official-documents.',
 'Any enquiries regarding this publication should be sent to us at\npublic.enquiries@hmtreasury.gov.uk']

In [116]:
pdf_text

'Sustainability Disclosure\nRequirements: Implementation\nUpdate 2024\nIntroduction - Sustainability Disclosure Requirements\n1.1 Mobilising Green Investment: 2023 Green Finance Strategy (2023) set out\nthe UK Government’s long-term strategy to ensure investors and consumers can\naccess the information they need to inform capital allocation in line with their\nsustainability preferences or goals.1 Central to this strategy is our plan for economy\nwide Sustainability Disclosure Requirements (SDR), as first set out in Greening\nFinance: A Roadmap to Sustainable Investing (2021).2 Building on global best\npractice and leading standards, SDR is a framework to facilitate and streamline the\nflow of robust, decision useful information between corporates, consumers and\ninvestors and capital markets.\n1.2 Financial markets are global, and international interoperability is a key\nprinciple of the UK’s approach to SDR. The 2023 Green Finance Strategy contained\na commitment to provide an SDR implementation update to reflect the rapid\ndevelopment of international standards. Following last year’s launch of the\nInternational Financial Reporting Standards (IFRS) Foundation’s International\nSustainability Standards Board (ISSB) baseline standards, this document provides\nthat update, setting out next steps on SDR and how industry can engage with the\ndevelopment of the different components.3\nComponents of SDR\nIFRS Sustainability Disclosure Standards\n1.3 The Government congratulated the ISSB on the publication of its inaugural\nstandards on 26 June 2023. The 2023 Green Finance Strategy explained that the\nGovernment is setting up an endorsement and implementation process for those\nstandards. The Government has today published a framework document which\nsets out further detail about that process and the advisory committees that will be\nsupporting the Government in taking this work forward. Please consult the\nframework document for further detail, including detail regarding the\nindependent UK Sustainability Disclosure Technical Advisory Committee that is\nbeing established to provide advice to the Secretary of State for Business and Trade\nwhen making an endorsement decision.4\n1.4 The Government aims to make the UK-endorsed ISSB standards\navailable in Q1 2025. The endorsement process will assess the standards and,\nsubject to a positive endorsement decision, will conclude with the publication of\n1 Mobilising Green Investment - 2023 Green Finance Strategy\n2 Greening Finance: A Roadmap to Sustainable Investing\n3 IFRS - IFRS Sustainability Standards Navigator\n4 Framework for Developing UK Sustainability Reporting Standards\nUK-endorsed standards. These will be known as UK Sustainability Reporting\nStandards.\n1.5 Subject to a positive endorsement decision by the UK Government, and\nfollowing a consultation process, the Financial Conduct Authority (FCA) will be\nable to use the UK Sustainability Reporting Standards to introduce\nrequirements for UK-listed companies to report sustainability-related\ninformation.\n1.6 Subject to a positive endorsement decision, the Government will also\ndecide on disclosure requirements against UK Sustainability Reporting\nStandards for UK companies that do not fall within the FCA’s regulatory\nperimeter. That decision will take into account a number of factors, including costs\nfor reporting companies and benefits for investors that may wish to use this\ninformation.\n1.7 The Government expects a decision regarding future requirements to be\ntaken in Q2 2025. At that time, the Government will also consider whether to\ncreate exemptions from pre-existing requirements in the Companies Act 2006 for\nthose companies that choose to use the standards on a voluntary basis. Any\ndecision that the Government takes on these matters will involve consultation and\nwill require Parliamentary approval for the introduction of any new legislation. As\na result, any changes that may be introduced would be effective no earlier than\naccounting periods beginning on or after 1 January 2026.\nTransition Plan Disclosures\n1.8 In April 2022, the Government launched the Transition Plan Taskforce (TPT)\nto develop a framework to help companies communicate their plan to achieve net\nzero to shareholders and other stakeholders.\n1.9 The Government, which co-chairs the TPT, is grateful for its important work,\nincluding the publication of their voluntary Disclosure Framework in October\n2023.5 The TPT’s Disclosure Framework has been designed purposefully to\nintegrate with and build from the approach to transition plans found in both the\nUK regulations6 and FCA rules7 that implement the Task Force on Climate-related\nFinancial Disclosures (TCFD) recommendations8 as well as the ISSB Standards and\nguidance from the Glasgow Financial Alliance for Net Zero (GFANZ) on transition\nplans.\n1.10 The ISSB’s climate-related disclosure standard, IFRS S2, includes a\nrequirement for companies to disclose details about their transition plan, if they\n5 The TPT Disclosure Framework | Transition Plan Taskforce\n6 Guidance on Climate-related financial disclosures for companies and limited liability partnerships\n7 FCA rules on TCFD-aligned reporting requirements\n8 TCFD recommendations\nhave one, and contains many disclosure requirements that are relevant to\ntransition planning. The TPT Disclosure Framework provides more detailed\nrecommendations on how to disclose effectively in line with these requirements.\n1.11 Given the overlap between IFRS S2 and the TPT Disclosure Framework, the\nFCA plans, through its consultation on implementing UK-endorsed ISSB\nstandards, to consult on strengthening its expectations for transition plan\ndisclosures with reference to the TPT Disclosure Framework.\n1.12 Given the important role of transition planning across the economy, the\nGovernment will consult shortly on how the UK’s largest companies can most\neffectively disclose their transition plans, meeting a key commitment of last\nyear’s Green Finance Strategy.\nSDR & Investment Labels\n1.13 The FCA finalised its Sustainability Disclosure Requirements (SDR) and\ninvestment labels regime for funds based in the UK, with the release of its policy\nstatement on 28 November 2023.9 The FCA engaged extensively with industry,\nincluding through their Disclosures and Labels Advisory Group, and carried out\nconsumer research to support the development of proposals and finalising the\nrules. 10\n1.14 The package of measures includes investment labels, naming and\nmarketing rules, an anti-greenwashing rule for all FCA-authorised firms, and\ndisclosure rules. The anti-greenwashing rule comes into effect on 31 May 2024 and\nother parts of the regime will be phased in. Firms will be able to use labels from 31\nJuly 2024, and naming and marketing requirements must be met by 2 December\n2024, with further disclosure requirements phased in over the next two years.\n1.15 In April 2024, the FCA published a consultation on extending the SDR\nand labelling regime to portfolio managers based in the UK, which is open until\n14 June 2024. The FCA also finalised its guidance on the anti-greenwashing rule,\nfollowing a consultation which closed in January 2024.\n1.16 In January 2024, the Government announced that it intends to consult\non whether to broaden the scope of SDR to include funds under the Overseas\nFunds Regime. The Government intends to issue this consultation in Q3 2024.\nUK Green Taxonomy\n1.17 The Government reiterated its commitment in the 2023 Green Finance\nStrategy to delivering a UK Green Taxonomy to help mobilise investment into\ngreen activities and tackle greenwashing. Developing a usable and useful\n9 PS23/16: Sustainability Disclosure Requirements (SDR) and investment labels | FCA\n10 DLAG Terms of Reference\ntaxonomy is a complex and technical exercise. The Government continues to\nwork at pace and expects to consult in due course on the proposed UK Green\nTaxonomy, seeking feedback on both the overarching framework and use cases,\nas well as the specific activity level criteria which defines green activities.\n1.18 After the Taxonomy has been finalised following consultation feedback, the\nGovernment will introduce a testing period for voluntary disclosures and use for at\nleast two reporting years before exploring mandating disclosures. The Government\nhas not yet made a decision on whether to introduce mandatory disclosures\nagainst the Taxonomy. Any decision on this would be subject to further\nconsultation and would take account of the evidence from the initial voluntary\nphase of reporting to ensure that any potential reporting against a future\nTaxonomy provides accessible and reliable information that is useful to markets.\nNature-Related Disclosures\n1.19 The Government welcomes initiatives such as the Taskforce on Nature-\nrelated Financial Disclosures (TNFD) which can help businesses and financial\ninstitutions assess and address their nature-related dependencies, impacts, risks,\nand opportunities. The Government congratulated the TNFD on the publication of\nits final recommendations, which launched at the New York Stock Exchange in\nSeptember 2023. The Government encourages institutions to engage in the TNFD\nUK National Consultation Group and consider the recommendations.\n1.20 The Government has followed with interest the ISSB’s Consultation on\nAgenda Priorities which recognises the importance of biodiversity, ecosystems,\necosystem services and human capital. It also notes the ISSB’s recent\nannouncement to commence research projects concerned with risk disclosure\nand opportunities associated with these issues, as part of an enhanced global\nbaseline of investor-focused sustainability disclosure.11 The Government continues\nto welcome the ongoing commitment of the ISSB to research and develop future\nadditional standards, which could also include reporting on nature-related risks\nand opportunities and encourages the ISSB to take the work and the holistic\nnature risk management approach of the TNFD into account at the appropriate\ntime.\n11 IFRS - ISSB to commence research projects about risks and opportunities related to nature and\nhuman capital\nFigure 1 – Timeline for SDR Implementation\nSDR Element Organisation 2024 2025\nQ2\n- Assessment of IFRS S1\nand IFRS S2 by the UK\nSustainability\nDisclosure Technical\nTechnical Advisory Committee\nAdvisory commences.\nCommittee12\nQ4\n- Assessment concludes\nand recommendations\nprovided to the\nSecretary of State for\nBusiness and Trade.\nQ1\n- Consultation on draft\nUK Sustainability\nReporting Standards\nIFRS\n- Endorsement decision\nSustainability\nand publication of UK\nDisclosure Sustainability\nStandards - Disclosure Standards,\nEndorsement & subject to a positive\nImplementation endorsement decision.\nof UK-endorsed UK\nISSB standards Government\nQ2\n- Subject to a positive\nendorsement decision,\nthe Government will\nconsult on disclosure\nrequirements against\nthe UK Sustainability\nReporting Standards for\nUK companies that do\nnot fall within the FCA’s\nregulatory perimeter.\n- Support progress - Subject to\ntowards adopting ISSB- endorsement process,\nbased sustainability consultation on\nFCA disclosures for listed updating TCFD-aligned\ncompanies. rules to UK\nSustainability Reporting\nStandards.\n12 UK Sustainability Disclosure Standards - GOV.UK (www.gov.uk)\nQ2\n- Consultation on the\nGovernment approach\nUK\nto transition plan\nGovernment\ndisclosures for UK\ncompanies.\n- Subject to\nTransition Plan\nendorsement process,\ndisclosure\nconsultation on\nstrengthening\ntransition plan\nFCA\ndisclosure expectations\nin line with TPT\nframework.\n- Consultation on - Subject to consultation\nwhether to broaden the outcomes, legislation\nscope of SDR to include required to implement\nUK\nfunds recognised under SDR and labelling for\nGovernment\nthe Overseas Funds OFR funds is likely to be\nRegime. published.\n- Staggered - Continued\nSDR & implementation of final implementation of final\nInvestment rules. rules.\nLabels - Consultation on\n- Subject to the\nextending the regime\noutcomes of the\nto portfolio managers\nGovernment’s\nFCA\nand final rules.\nconsultation, FCA will\n- Final anti-\nfollow a separate\ngreenwashing\nprocess to consult and\nguidance.\nmake rules for overseas\nfunds.\n- Launch of consultation\nUK Green UK\non the design of the UK\nTaxonomy Government\nGreen Taxonomy.\n© Crown copyright 2023\nThis publication is licensed under the terms of the Open Government\nLicence v3.0 except where otherwise stated. To view this licence, visit\nnationalarchives.gov.uk/doc/open-government-licence/version/3.\nWhere we have identified any third party copyright information you\nwill need to obtain permission from the copyright holders concerned.\nThis publication is available at: www.gov.uk/official-documents.\nAny enquiries regarding this publication should be sent to us at\npublic.enquiries@hmtreasury.gov.uk\n'

In [7]:
sentences[1]

'1.2 Financial markets are global, and international interoperability is a key\nprinciple of the UK’s approach to SDR.'

In [8]:
import string
import re
def text_clean_1(text):
    text = text.lower()
    text= text.replace("\n","");
    text= text.replace("            ","");
    return text

In [10]:
len(sentences)

62

In [11]:
sdr_clean=[]
for i in range(len(sentences)):
    sdr_clean.append(text_clean_1(str(sentences[i])))
#print(len(t_parag))
sdr_clean

['sustainability disclosurerequirements: implementationupdate 2024introduction - sustainability disclosure requirements1.1 mobilising green investment: 2023 green finance strategy (2023) set outthe uk government’s long-term strategy to ensure investors and consumers canaccess the information they need to inform capital allocation in line with theirsustainability preferences or goals.1 central to this strategy is our plan for economywide sustainability disclosure requirements (sdr), as first set out in greeningfinance: a roadmap to sustainable investing (2021).2 building on global bestpractice and leading standards, sdr is a framework to facilitate and streamline theflow of robust, decision useful information between corporates, consumers andinvestors and capital markets.',
 '1.2 financial markets are global, and international interoperability is a keyprinciple of the uk’s approach to sdr.',
 'the 2023 green finance strategy containeda commitment to provide an sdr implementation update to reflect the rapiddevelopment of international standards.',
 'following last year’s launch of theinternational financial reporting standards (ifrs) foundation’s internationalsustainability standards board (issb) baseline standards, this document providesthat update, setting out next steps on sdr and how industry can engage with thedevelopment of the different components.3components of sdrifrs sustainability disclosure standards1.3 the government congratulated the issb on the publication of its inauguralstandards on 26 june 2023.',
 'the 2023 green finance strategy explained that thegovernment is setting up an endorsement and implementation process for thosestandards.',
 'the government has today published a framework document whichsets out further detail about that process and the advisory committees that will besupporting the government in taking this work forward.',
 'please consult theframework document for further detail, including detail regarding theindependent uk sustainability disclosure technical advisory committee that isbeing established to provide advice to the secretary of state for business and tradewhen making an endorsement decision.41.4 the government aims to make the uk-endorsed issb standardsavailable in q1 2025.',
 'the endorsement process will assess the standards and,subject to a positive endorsement decision, will conclude with the publication of1 mobilising green investment - 2023 green finance strategy2 greening finance: a roadmap to sustainable investing3 ifrs - ifrs sustainability standards navigator4 framework for developing uk sustainability reporting standardsuk-endorsed standards.',
 'these will be known as uk sustainability reportingstandards.',
 '1.5 subject to a positive endorsement decision by the uk government, andfollowing a consultation process, the financial conduct authority (fca) will beable to use the uk sustainability reporting standards to introducerequirements for uk-listed companies to report sustainability-relatedinformation.',
 '1.6 subject to a positive endorsement decision, the government will alsodecide on disclosure requirements against uk sustainability reportingstandards for uk companies that do not fall within the fca’s regulatoryperimeter.',
 'that decision will take into account a number of factors, including costsfor reporting companies and benefits for investors that may wish to use thisinformation.',
 '1.7 the government expects a decision regarding future requirements to betaken in q2 2025.',
 'at that time, the government will also consider whether tocreate exemptions from pre-existing requirements in the companies act 2006 forthose companies that choose to use the standards on a voluntary basis.',
 'anydecision that the government takes on these matters will involve consultation andwill require parliamentary approval for the introduction of any new legislation.',
 'asa result, any changes that may be introduced would be effective no earlier thanaccounting periods beginning on or after 1 january 2026.',
 'transition plan disclosures1.8 in april 2022, the government launched the transition plan taskforce (tpt)to develop a framework to help companies communicate their plan to achieve netzero to shareholders and other stakeholders.',
 '1.9 the government, which co-chairs the tpt, is grateful for its important work,including the publication of their voluntary disclosure framework in october2023.5 the tpt’s disclosure framework has been designed purposefully tointegrate with and build from the approach to transition plans found in both theuk regulations6 and fca rules7 that implement the task force on climate-relatedfinancial disclosures (tcfd) recommendations8 as well as the issb standards andguidance from the glasgow financial alliance for net zero (gfanz) on transitionplans.',
 '1.10 the issb’s climate-related disclosure standard, ifrs s2, includes arequirement for companies to disclose details about their transition plan, if they5 the tpt disclosure framework | transition plan taskforce6 guidance on climate-related financial disclosures for companies and limited liability partnerships7 fca rules on tcfd-aligned reporting requirements8 tcfd recommendationshave one, and contains many disclosure requirements that are relevant totransition planning.',
 'the tpt disclosure framework provides more detailedrecommendations on how to disclose effectively in line with these requirements.',
 '1.11 given the overlap between ifrs s2 and the tpt disclosure framework, thefca plans, through its consultation on implementing uk-endorsed issbstandards, to consult on strengthening its expectations for transition plandisclosures with reference to the tpt disclosure framework.',
 '1.12 given the important role of transition planning across the economy, thegovernment will consult shortly on how the uk’s largest companies can mosteffectively disclose their transition plans, meeting a key commitment of lastyear’s green finance strategy.',
 'sdr & investment labels1.13 the fca finalised its sustainability disclosure requirements (sdr) andinvestment labels regime for funds based in the uk, with the release of its policystatement on 28 november 2023.9 the fca engaged extensively with industry,including through their disclosures and labels advisory group, and carried outconsumer research to support the development of proposals and finalising therules.',
 '101.14 the package of measures includes investment labels, naming andmarketing rules, an anti-greenwashing rule for all fca-authorised firms, anddisclosure rules.',
 'the anti-greenwashing rule comes into effect on 31 may 2024 andother parts of the regime will be phased in.',
 'firms will be able to use labels from 31july 2024, and naming and marketing requirements must be met by 2 december2024, with further disclosure requirements phased in over the next two years.',
 '1.15 in april 2024, the fca published a consultation on extending the sdrand labelling regime to portfolio managers based in the uk, which is open until14 june 2024.',
 'the fca also finalised its guidance on the anti-greenwashing rule,following a consultation which closed in january 2024.',
 '1.16 in january 2024, the government announced that it intends to consulton whether to broaden the scope of sdr to include funds under the overseasfunds regime.',
 'the government intends to issue this consultation in q3 2024.',
 'uk green taxonomy1.17 the government reiterated its commitment in the 2023 green financestrategy to delivering a uk green taxonomy to help mobilise investment intogreen activities and tackle greenwashing.',
 'developing a usable and useful9 ps23/16: sustainability disclosure requirements (sdr) and investment labels | fca10 dlag terms of referencetaxonomy is a complex and technical exercise.',
 'the government continues towork at pace and expects to consult in due course on the proposed uk greentaxonomy, seeking feedback on both the overarching framework and use cases,as well as the specific activity level criteria which defines green activities.',
 '1.18 after the taxonomy has been finalised following consultation feedback, thegovernment will introduce a testing period for voluntary disclosures and use for atleast two reporting years before exploring mandating disclosures.',
 'the governmenthas not yet made a decision on whether to introduce mandatory disclosuresagainst the taxonomy.',
 'any decision on this would be subject to furtherconsultation and would take account of the evidence from the initial voluntaryphase of reporting to ensure that any potential reporting against a futuretaxonomy provides accessible and reliable information that is useful to markets.',
 'nature-related disclosures1.19 the government welcomes initiatives such as the taskforce on nature-related financial disclosures (tnfd) which can help businesses and financialinstitutions assess and address their nature-related dependencies, impacts, risks,and opportunities.',
 'the government congratulated the tnfd on the publication ofits final recommendations, which launched at the new york stock exchange inseptember 2023.',
 'the government encourages institutions to engage in the tnfduk national consultation group and consider the recommendations.',
 '1.20 the government has followed with interest the issb’s consultation onagenda priorities which recognises the importance of biodiversity, ecosystems,ecosystem services and human capital.',
 'it also notes the issb’s recentannouncement to commence research projects concerned with risk disclosureand opportunities associated with these issues, as part of an enhanced globalbaseline of investor-focused sustainability disclosure.11 the government continuesto welcome the ongoing commitment of the issb to research and develop futureadditional standards, which could also include reporting on nature-related risksand opportunities and encourages the issb to take the work and the holisticnature risk management approach of the tnfd into account at the appropriatetime.',
 '11 ifrs - issb to commence research projects about risks and opportunities related to nature andhuman capitalfigure 1 – timeline for sdr implementationsdr element organisation 2024 2025q2- assessment of ifrs s1and ifrs s2 by the uksustainabilitydisclosure technicaltechnical advisory committeeadvisory commences.',
 'committee12q4- assessment concludesand recommendationsprovided to thesecretary of state forbusiness and trade.',
 'q1- consultation on draftuk sustainabilityreporting standardsifrs- endorsement decisionsustainabilityand publication of ukdisclosure sustainabilitystandards - disclosure standards,endorsement & subject to a positiveimplementation endorsement decision.',
 'of uk-endorsed ukissb standards governmentq2- subject to a positiveendorsement decision,the government willconsult on disclosurerequirements againstthe uk sustainabilityreporting standards foruk companies that donot fall within the fca’sregulatory perimeter.',
 '- support progress - subject totowards adopting issb- endorsement process,based sustainability consultation onfca disclosures for listed updating tcfd-alignedcompanies.',
 'rules to uksustainability reportingstandards.',
 '12 uk sustainability disclosure standards - gov.uk (www.gov.uk)q2- consultation on thegovernment approachukto transition plangovernmentdisclosures for ukcompanies.',
 '- subject totransition planendorsement process,disclosureconsultation onstrengtheningtransition planfcadisclosure expectationsin line with tptframework.',
 '- consultation on - subject to consultationwhether to broaden the outcomes, legislationscope of sdr to include required to implementukfunds recognised under sdr and labelling forgovernmentthe overseas funds ofr funds is likely to beregime.',
 'published.',
 '- staggered - continuedsdr & implementation of final implementation of finalinvestment rules.',
 'rules.',
 'labels - consultation on- subject to theextending the regimeoutcomes of theto portfolio managersgovernment’sfcaand final rules.',
 'consultation, fca will- final anti-follow a separategreenwashingprocess to consult andguidance.',
 'make rules for overseasfunds.',
 '- launch of consultationuk green ukon the design of the uktaxonomy governmentgreen taxonomy.',
 '© crown copyright 2023this publication is licensed under the terms of the open governmentlicence v3.0 except where otherwise stated.',
 'to view this licence, visitnationalarchives.gov.uk/doc/open-government-licence/version/3.',
 'where we have identified any third party copyright information youwill need to obtain permission from the copyright holders concerned.',
 'this publication is available at: www.gov.uk/official-documents.',
 'any enquiries regarding this publication should be sent to us atpublic.enquiries@hmtreasury.gov.uk']

In [12]:
type(sdr_clean[1])

str

In [18]:
len(sdr_clean)

62

In [24]:
import os
# from openai import OpenAI  <-- Replace this
from langfuse.openai import OpenAI

# 1. Initialize credentials
os.environ["LANGFUSE_PUBLIC_KEY"] = ""
os.environ["LANGFUSE_SECRET_KEY"] = ""
os.environ["LANGFUSE_HOST"] = ""

In [25]:
client = OpenAI()
# 2. Tell LiteLLM to send data to Langfuse
litellm.success_callback = ["langfuse"]
# 2. Use as normal - Langfuse automatically creates a trace
response = client.chat.completions.create(
    model="gpt-4o-mini",
    name="summary-gen", # Optional: Name the generation in Langfuse
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Explain sustainable finance concepts in laymens terms."}
    ]
    #,metadata={"customer_id": "user_1234"} # Optional: Add custom metadata
)

print(response.choices[0].message.content)

Sure! Sustainable finance is a way of managing money that focuses on making sure that financial decisions are good for people and the planet, not just for making a profit. Here are some key concepts in simple terms:

1. **Sustainability**: This means keeping our environment healthy and making sure our society works well for everyone, both now and in the future. It’s about balancing economic growth with protecting nature and ensuring social equity.

2. **Responsible Investing**: This is when investors choose to put their money into companies or projects that are doing good things, like using clean energy or treating their workers fairly. They avoid investing in businesses that harm the environment or exploit people.

3. **Environmental, Social, and Governance (ESG) Criteria**: These are the guidelines investors use to evaluate how well a company is doing in terms of sustainability:
   - **Environmental**: How does the company impact the planet? Do they pollute or use renewable resources?
   - **Social**: How does the company treat people? Do they support their workers and the community?
   - **Governance**: How is the company run? Is it fair, transparent, and accountable to its shareholders?

4. **Green Bonds**: These are loans that are specifically used to fund projects that are good for the environment, like building solar farms or improving energy efficiency. Investors buy these bonds, and the money is used for eco-friendly initiatives.

5. **Impact Investing**: This means investing in companies or projects specifically to make a positive impact, alongside earning a financial return. For example, investing in a company that provides clean water solutions in developing countries.

6. **Socially Responsible Funds**: These are investment funds that only include companies that meet certain ethical standards, such as not producing harmful products or treating their employees unfairly.

7. **Climate Finance**: This refers to the financial resources needed to help tackle climate change, such as funding for renewable energy or efforts to protect vulnerable communities from climate impacts.

8. **Divestment**: This is the process of withdrawing investments from companies or industries that are considered harmful, especially fossil fuels, in order to signal that investors want to move towards more sustainable options.

In essence, sustainable finance is about making smart financial choices that contribute to a better world. It encourages individuals and organizations to think about the impact of their money on society and the environment, aiming for a future where economic growth does not come at the expense of our planet or communities.

In [51]:
prompt_list=[f"Extract related entities from these {sdr_clean[1]}", f"Give me the topic of this {sdr_clean[1]}"]
print(type(prompt_list))
print(len(prompt_list))

<class 'list'>
2

In [47]:
import pandas as pd

def research_assistant(prompt_list):
    all_results = []

    for prompt in prompt_list:
        print(f"Running prompt: {prompt[:50]}...") # Progress tracker
        
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            # Note: 'name' is usually for the 'message' role in some SDKs, 
            # but for a standard call, we just use messages.
            messages=[{"role": "user", "content": prompt}]
        )
        
        # Extract the content
        content = response.choices[0].message.content
        
        # Store as a dictionary for easy conversion to Excel/DataFrame
        all_results.append({
            "Prompt": prompt,
            "Response": content
        })
        
    return all_results

# Your prompt list
prompt_list = [
    f"Extract entities from these {sdr_clean[1]}", 
    f"Give me the topic of this {sdr_clean[1]}"
]
for i in range(len(sdr_clean)):
    print(i)
    print( f"Extract entities from this sentence {sdr_clean[i]}")

# Execute
results = research_assistant(prompt_list)
results

Running prompt: Extract entities from these 1.2 financial markets ...
Running prompt: Give me the topic of this 1.2 financial markets ar...

[{'Prompt': 'Extract entities from these 1.2 financial markets are global, and international interoperability is a keyprinciple of the uk’s approach to sdr.',
  'Response': 'Here are the extracted entities from the provided text:\n\n1. **Financial markets** - General concept.\n2. **Global** - Descriptor for the financial markets.\n3. **International interoperability** - Concept/principle.\n4. **UK (United Kingdom)** - Country.\n5. **SDR (Special Drawing Rights)** - Financial instrument or concept. \n\nWould you like more detailed explanations or context for any of these entities?'},
 {'Prompt': 'Give me the topic of this 1.2 financial markets are global, and international interoperability is a keyprinciple of the uk’s approach to sdr.',
  'Response': "The topic of the statement refers to the global nature of financial markets and the importance of international interoperability, particularly in the context of the UK's approach to Special Drawing Rights (SDR). This highlights how countries collaborate and synchronize their financial systems to facilitate international trade, investment, and economic stability."}]

In [127]:
from langfuse import observe
import os
client = OpenAI()

@observe()
def research_assistant(text: str):
    # Step 1: Search/Reasoning (Generation 1)
    entities = client.chat.completions.create(
        model="gpt-4o-mini",
        name="planning-step",
        messages=[{"role": "user", "content": f"""You are aiming to create a knowledge graph. Your task is to extract all defined terms, entities, relationships between entities and legally relevant concepts from the following Sustainable Disclosure Requirements (SDR) document {text}.

Instructions:
- Extract every defined term or entity-relationships-entity as a clean list.
- Categorise the entities as concept, organisations, sectors, group, financial ters or metrics
- Include names of organizations, roles, regulations, laws, and standards mentioned.
- Do not deduplicate similar terms—list each occurrence separately if it appears in the text.
- For each extracted term, include:
- The exact term or entity as it appears
- If available, its definition or a short excerpt of the sentence where it was defined
- Present the results in a clean bullet-point list in markdown."""}]
        ).choices[0].message.content   
    return entities   

    # Step 2: Final Answer (Generation 2)
   # final_report = client.chat.completions.create(
   #     model="gpt-4o-mini",
   #     name="final-report",
   #     messages=[{"role": "user", "content": f"Write a report based on this plan: {plan}"}]
   # ).choices[0].message.content
   #   

# This call will show up in Langfuse as one 'Trace' containing two 'Generations'
result=research_assistant(pdf_text)

In [201]:
import pandas as pd
import json

def run_research_and_export(sentence_list, manual_prompt, file_name="SDR_Output_P1.xlsx"):
    flattened_data = []
    print(manual_prompt)
    for s_index, sentence in enumerate(sentence_list):
        print(f"Processing {s_index + 1}/{len(sentence_list)}...")
        print(sentence)
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": f"{manual_prompt}\n\nSentence: {sentence}"}]
        )
        content = response.choices[0].message.content.strip()
        print(content)

        try:
            # Clean and parse JSON
            clean_content = content.replace("```json", "").replace("```", "").strip()
            data = json.loads(clean_content)
            
            # Navigate to the list of terms
            # Based on your image, it looks like 'terms' is the main key
            items = data.get('terms', data.get('entities', []))

            if isinstance(items, list):
                for item in items:
                    if isinstance(item, dict):
                        # MAPPING: 'term' -> Entity, 'category' -> Category
                        flattened_data.append({
                            'Sentence': sentence.replace('\n', ' '),
                            'Category': item.get('category', 'N/A'),
                            'Entity': item.get('term', 'N/A'),
                            'Value': item.get('term', 'N/A') # Or use a description if available
                        })
            elif isinstance(items, dict):
                # Fallback for the { 'UK': 'United Kingdom' } format
                for cat, entities in items.items():
                    if isinstance(entities, list):
                        for e in entities:
                            flattened_data.append({
                                'Sentence': sentence.replace('\n', ' '),
                                'Category': cat,
                                'Entity': e,
                                'Value': e
                            })

        except Exception as e:
            print(f"Error parsing JSON: {e}")
            flattened_data.append({
                'Sentence': sentence,
                'Category': 'Error',
                'Entity': 'Raw Response',
                'Value': content
            })

    # Export
    df = pd.DataFrame(flattened_data)
    df.to_excel(file_name, index=False)
    
    print(f"✅ Fixed! Data exported to {file_name}")

In [204]:
prompt1="""Extract all defined terms, ENTITIES and their categories from this SUSTAINABLE DISCLOSURE REQUIREMENTS document AS A name entity recognizer specialist. Output should be in JSON format, Include capitalized terms, terms in quotation marks, and those introduced by phrases like 'means' or 'shall be understood as and only show extracted entities in the output"""

In [211]:
prompt2 = """
You are an expert Ontology Engineer. Extract triples (Subject-Predicate-Object) from the provided regulatory text.
For every entity extracted as a Subject or Object, you MUST also identify its Category.

For each extraction, output exactly in this JSON format:
{
  "triples": [
    {
      "subject": "<entity name>",
      "subject_category": "<category of subject>",
      "predicate": "<relationship verb or phrase>",
      "object": "<entity name>",
      "object_category": "<category of object>"
    }
  ]
}

Guidelines:
- Categorize entities as (e.g., Organization, Concept, Document, Process, Date, or Regulation).
- Only extract explicit relationships defined in the text.
- Provide ONLY the JSON array. Do not include introductory text.
"""

In [215]:
def run_research_and_export_rel_v2(sentence_list, manual_prompt, file_name="SDR_P2.xlsx"):
    flattened_data = []
    
    for s_index, sentence in enumerate(sentence_list):
        print(f"Processing {s_index + 1}/{len(sentence_list)}...")
        
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": f"{manual_prompt}\n\nSentence: {sentence}"}],
            temperature=0 # Set to 0 for consistent extraction
        )
        
        content = response.choices[0].message.content.strip()

        try:
            # Clean and parse JSON
            clean_content = content.replace("```json", "").replace("```", "").strip()
            data = json.loads(clean_content)
            
            # Access the 'triples' key defined in the prompt
            items = data.get('triples', [])

            for item in items:
                flattened_data.append({
                    'Sentence': sentence.replace('\n', ' '),
                    'Subject': item.get('subject', 'N/A'),
                    'Subject_Category': item.get('subject_category', 'N/A'),
                    'Predicate': item.get('predicate', 'N/A'),
                    'Object': item.get('object', 'N/A'),
                    'Object_Category': item.get('object_category', 'N/A')
                })

        except Exception as e:
            print(f"Error parsing JSON on sentence {s_index}: {e}")
            # Optional: Log the error to the dataframe to see what failed
            
    # Export to Excel
    df = pd.DataFrame(flattened_data)
    df.to_excel(file_name, index=False)
    print(f"✅ Success! Triples with categories exported to {file_name}")

# To run:
# run_research_and_export_rel_v2(sentence_list, prompt2)

In [216]:
run_research_and_export(sdr_clean, prompt1)
run_research_and_export_rel_v2(sdr_clean, prompt2)

Processing 1/62...
Processing 2/62...
Processing 3/62...
Processing 4/62...
Processing 5/62...
Processing 6/62...
Processing 7/62...
Processing 8/62...
Processing 9/62...
Processing 10/62...
Processing 11/62...
Processing 12/62...
Processing 13/62...
Processing 14/62...
Processing 15/62...
Processing 16/62...
Processing 17/62...
Processing 18/62...
Processing 19/62...
Processing 20/62...
Processing 21/62...
Processing 22/62...
Processing 23/62...
Processing 24/62...
Processing 25/62...
Processing 26/62...
Processing 27/62...
Processing 28/62...
Processing 29/62...
Processing 30/62...
Processing 31/62...
Processing 32/62...
Processing 33/62...
Processing 34/62...
Processing 35/62...
Processing 36/62...
Processing 37/62...
Processing 38/62...
Processing 39/62...
Processing 40/62...
Processing 41/62...
Processing 42/62...
Processing 43/62...
Processing 44/62...
Processing 45/62...
Processing 46/62...
Processing 47/62...
Processing 48/62...
Processing 49/62...
Processing 50/62...
Processing 51/62...
Processing 52/62...
Processing 53/62...
Processing 54/62...
Processing 55/62...
Processing 56/62...
Processing 57/62...
Processing 58/62...
Processing 59/62...
Processing 60/62...
Processing 61/62...
Processing 62/62...
✅ Success! Triples with categories exported to SDR_P2.xlsx

In [217]:
data_p1=pd.read_excel(r"C:\Users\Buket Fildisi\Desktop\PhD\LLM\SDR_Output_P1.xlsx")
data_p2= pd.read_excel(r"C:\Users\Buket Fildisi\Desktop\PhD\LLM\SDR_P2.xlsx")
data_neo4j= pd.read_excel(r"C:\Users\Buket Fildisi\Desktop\PhD\LLM\SDR_NEO4J_ENTITYLabels.xlsx")
gold= pd.read_excel(r"C:\Users\Buket Fildisi\Desktop\SDR_ValidationSet.xlsx")
gold.head()

,Source Sentence,Entity,Category
0,1.11 Given the overlap between IFRS S2 and the...,IFRS S2,STANDARD
1,1.11 Given the overlap between IFRS S2 and the...,TPT Disclosure Framework,FRAMEWORK
2,1.11 Given the overlap between IFRS S2 and the...,FCA,Organization
3,1.11 Given the overlap between IFRS S2 and the...,UK-endorsed ISSB standards,STANDARD
4,1.11 Given the overlap between IFRS S2 and the...,ISSB,Organization

In [261]:
data_neo4j_trip= pd.read_excel(r"C:\Users\Buket Fildisi\Desktop\PhD\LLM\SDR_NEO4J_ENTITYLabels.xlsx", sheet_name="Triples")
data_neo4j_trip.head()

,Subject,Predicate,Object
0,Government,AIMS_TO_MAKE_AVAILABLE,UK-endorsed ISSB standards
1,Government,ANNOUNCED_INTENTION,consult on whether to broaden the scope of SDR...
2,UK Sustainability Reporting Standards,APPLIES_TO,UK companies that do not fall within the FCAâ€...
3,investment labels regime for funds based in th...,APPLIES_TO,funds based in the UK
4,anti-greenwashing rule,APPLIES_TO,FCA-authorised firms

In [243]:
gold_triples= pd.read_excel(r"C:\Users\Buket Fildisi\Desktop\SDR_ValidationSet.xlsx", sheet_name="Relationships")
gold_triples

,Sentences,Subject,Subject Category,Predicate,Object,Object Category
0,1.11,IFRS S2,STANDARD,overlaps with,TPT Disclosure Framework,FRAMEWORK
1,1.11,FCA,Organization,plans to consult on,Transition plan disclosures,Concept
2,1.11,FCA,Organization,references,TPT Disclosure Framework,POLICY_MECHANISM
3,1.12,UK Government,Organization,will consult on,Transition plans,Plan
4,1.12,Transition plans,Plan,meets commitment of,Green Finance Strategy,Policy_Strategy
5,1.13,FCA,Organization,finalised,SDR,Regulation
6,1.13,FCA,Organization,finalised,Investment labels regime,Policy_Framework
7,1.13,SDR Policy Statement,Policy_Document,released on,2023-11-28 00:00:00,Date
8,1.13,FCA,Organization,engaged with,Disclosures & Labels Advisory Group,Organization
9,1.14,SDR Package,Regulation,includes,Investment labels,POLICY_MECHANISM
10,1.14,SDR Package,Regulation,includes,Anti-greenwashing rule,Regulation
11,1.14,Anti-greenwashing rule,Regulation,effective from,2024-05-31 00:00:00,Date
12,1.14,Firms,Actor,use labels from,2024-07-31 00:00:00,Date
13,1.14,Marketing requirements,Regulation,deadline,2024-12-02 00:00:00,Date
14,1.15,FCA,Organization,consults on extending,Portfolio managers,FINANCIAL_ACTOR
15,1.15,Consultation,Process,closes on,2024-06-14 00:00:00,Date
16,1.16,SDR Scope,Concept,broaden to include,Overseas Funds Regime,Regulation
17,1.16,Consultation,Process,expected in,Q3 2024,Date

In [244]:
data_p2.head()

,Sentence,Subject,Subject_Category,Predicate,Object,Object_Category
0,sustainability disclosurerequirements: impleme...,UK Government,Organization,set out,2023 Green Finance Strategy,Document
1,sustainability disclosurerequirements: impleme...,2023 Green Finance Strategy,Document,ensure,investors and consumers,Organization
2,sustainability disclosurerequirements: impleme...,investors and consumers,Organization,can access,information,Concept
3,sustainability disclosurerequirements: impleme...,information,Concept,to inform,capital allocation,Process
4,sustainability disclosurerequirements: impleme...,sustainability disclosure requirements (SDR),Concept,is,a framework,Concept

In [224]:
def normalize_text(x):
    return str(x).strip().lower().replace("\n", " ")
alias_map = {
    "sustainability disclosure requirements": "sdr",
    "financial conduct authority": "fca"
}

In [225]:
gold[['Category', 'Entity']]

            Category                                  Entity
0           STANDARD                                 IFRS S2
1          FRAMEWORK                TPT Disclosure Framework
2       Organization                                     FCA
3           STANDARD              UK-endorsed ISSB standards
4       Organization                                    ISSB
5   POLICY_MECHANISM             transition plan disclosures
6       Organization                              Government
7            Country                                      UK
8    FINANCIAL_ACTOR                  UK’s largest companies
9               Plan                     transition planning
10              Plan                        transition plans
11   Policy_Strategy                  Green Finance Strategy
12      Organization                                     FCA
13        REGULATION  Sustainability Disclosure Requirements
14        REGULATION                                     SDR
15  Policy_Framework                investment labels regime
16   FINANCIAL_ACTOR                                   funds
17           Country                                      UK
18   Policy_Document                        policy statement
19              DATE                     2023-11-28 00:00:00
20      ORGANISATION   Disclosures and Labels Advisory Group
21   FINANCIAL_ACTOR                                industry
22  POLICY_MECHANISM                       investment labels
23        REGULATION              naming and marketing rules
24        REGULATION                  anti-greenwashing rule
25      ORGANIZATION                    FCA-authorised firms
26        REGULATION                        disclosure rules
27        REGULATION                  anti-greenwashing rule
28              DATE                     2024-05-31 00:00:00
29  Policy_Framework                                  regime
30      Organization                                   Firms
31  POLICY_MECHANISM                                  labels
32              DATE                     2024-07-31 00:00:00
33        REGULATION       naming and marketing requirements
34              DATE                     2024-12-02 00:00:00
35        REGULATION                 disclosure requirements
36              DATE                     2024-04-01 00:00:00
37      Organization                                     FCA
38        REGULATION                                     SDR
39  Policy_Framework                        labelling regime
40   FINANCIAL_ACTOR                      portfolio managers
41           Country                                      UK
42              DATE                     2024-06-14 00:00:00

In [237]:
data_p2.head()

,Sentence,Subject,Subject_Category,Predicate,Object,Object_Category
0,sustainability disclosurerequirements: impleme...,UK Government,Organization,set out,2023 Green Finance Strategy,Document
1,sustainability disclosurerequirements: impleme...,2023 Green Finance Strategy,Document,ensure,investors and consumers,Organization
2,sustainability disclosurerequirements: impleme...,investors and consumers,Organization,can access,information,Concept
3,sustainability disclosurerequirements: impleme...,information,Concept,to inform,capital allocation,Process
4,sustainability disclosurerequirements: impleme...,sustainability disclosure requirements (SDR),Concept,is,a framework,Concept

In [257]:
data_neo4j.head()

                             Entity         Category
0               2023-10-01 00:00:00             Date
1     make rules for overseas funds           Action
2  Final anti-greenwashing guidance   Policy, Action
3                 UK Green Taxonomy          Concept
4                      consultation   Report, Action

In [258]:
# Convert specific columns to a list of dictionaries
# This replaces your old 'item in extracted_data' logic
entity_data = data_p1[['Category', 'Entity', 'Sentence']].to_dict('records')
entity_data_nj = data_neo4j[['Category', 'Entity']].to_dict('records')
print(entity_data_nj)
# If you just need a list of strings for the embedding model input:
entities_list = entity_data_nj['Entity'].astype(str).tolist()

[{'Category': ' Date', 'Entity': datetime.datetime(2023, 10, 1, 0, 0)}, {'Category': ' Action', 'Entity': 'make rules for overseas funds'}, {'Category': ' Policy, Action', 'Entity': 'Final anti-greenwashing guidance'}, {'Category': ' Concept', 'Entity': 'UK Green Taxonomy'}, {'Category': ' Report, Action', 'Entity': 'consultation'}, {'Category': ' Organization', 'Entity': 'Financial Conduct Authority (FCA)'}, {'Category': ' Organization, Government Entity', 'Entity': 'UK Government'}, {'Category': ' Action', 'Entity': 'Consultation on extending the regime to portfolio managers and final rules'}, {'Category': ' Action', 'Entity': 'Consultation on strengthening transition plan disclosure expectations in line with TPT framework'}, {'Category': ' Action', 'Entity': 'Staggered implementation of final rules'}, {'Category': ' Concept,  Policy', 'Entity': 'UK Sustainability Reporting Standards'}, {'Category': ' Action', 'Entity': 'Assessment concludes and recommendations provided'}, {'Category': ' Action', 'Entity': 'Assessment of IFRS S1 and IFRS S2'}, {'Category': ' Action', 'Entity': 'Consultation on draft UK Sustainability Reporting Standards'}, {'Category': ' Action', 'Entity': 'Endorsement decision and publication of UK Sustainability Disclosure Standards'}, {'Category': ' Organization', 'Entity': 'UK Sustainability Disclosure Technical Advisory Committee'}, {'Category': ' Concept', 'Entity': 'holistic nature risk management approach of the TNFD'}, {'Category': ' Organization', 'Entity': 'IFRS'}, {'Category': ' Characteristic', 'Entity': 'use cases'}, {'Category': ' Action', 'Entity': 'further consultation'}, {'Category': ' Action', 'Entity': 'mandatory disclosures'}, {'Category': ' Characteristic', 'Entity': 'specific activity level criteria'}, {'Category': ' Characteristic', 'Entity': 'overarching framework'}, {'Category': ' Action', 'Entity': 'initial voluntary phase of reporting'}, {'Category': ' Action', 'Entity': 'consultation feedback'}, {'Category': ' Concept', 'Entity': 'Sendai Framework for Disaster Risk Reduction 2015â€“2030'}, {'Category': ' Action', 'Entity': 'Parliamentary approval'}, {'Category': ' Date', 'Entity': datetime.datetime(2023, 10, 1, 0, 0)}, {'Category': ' Report', 'Entity': 'Disclosure Framework'}, {'Category': ' Characteristic', 'Entity': 'voluntary'}, {'Category': ' Characteristic', 'Entity': 'UK-endorsed standards'}, {'Category': ' Activity', 'Entity': 'work'}, {'Category': ' Report', 'Entity': 'IFRS - IFRS Sustainability Standards Navigator'}, {'Category': ' Report', 'Entity': 'Mobilising Green Investment - 2023 Green Finance Strategy'}, {'Category': ' Concept, Report', 'Entity': 'framework document'}, {'Category': ' Report', 'Entity': 'Greening Finance: A Roadmap to Sustainable Investing'}, {'Category': ' Characteristic', 'Entity': 'further detail about that process'}, {'Category': ' Action', 'Entity': 'International Sustainability Standards Board (ISSB) baseline standards'}, {'Category': ' Concept', 'Entity': 'ESG information'}, {'Category': ' Market', 'Entity': 'global financial markets'}, {'Category': ' Characteristic', 'Entity': 'international interoperability'}, {'Category': ' Concept', 'Entity': 'UKâ€™s approach to SDR'}, {'Category': ' Characteristic', 'Entity': 'use cases'}, {'Category': ' Action', 'Entity': 'further consultation'}, {'Category': ' Action', 'Entity': 'mandatory disclosures'}, {'Category': ' Characteristic', 'Entity': 'specific activity level criteria'}, {'Category': ' Characteristic', 'Entity': 'overarching framework'}, {'Category': ' Action', 'Entity': 'initial voluntary phase of reporting'}, {'Category': ' Action', 'Entity': 'consultation feedback'}, {'Category': ' Concept', 'Entity': 'UK Green Taxonomy'}, {'Category': ' Organization, Government Entity', 'Entity': 'UK Government'}, {'Category': ' Concept', 'Entity': 'Sendai Framework for Disaster Risk Reduction 2015â€“2030'}, {'Category': ' Action', 'Entity': 'Parliamentary approval'}, {'Category': ' Report, Action', 'Entity': 'consultation'}, {'Category': ' Date', 'Entity': datetime.datetime(2023, 10, 1, 0, 0)}, {'Category': ' Report', 'Entity': 'Disclosure Framework'}, {'Category': ' Characteristic', 'Entity': 'voluntary'}, {'Category': ' Activity,  Concept', 'Entity': 'CDP reporting'}, {'Category': ' Concept', 'Entity': 'sustainability efforts'}, {'Category': ' Organization', 'Entity': 'Financial Conduct Authority (FCA)'}, {'Category': ' Concept,  Policy', 'Entity': 'UK Sustainability Reporting Standards'}, {'Category': ' Concept', 'Entity': 'holistic nature risk management approach of the TNFD'}, {'Category': ' Organization', 'Entity': 'IFRS'}, {'Category': ' Characteristic', 'Entity': 'UK-endorsed standards'}, {'Category': ' Concept', 'Entity': 'ESG information'}, {'Category': ' Market', 'Entity': 'global financial markets'}, {'Category': ' Characteristic', 'Entity': 'international interoperability'}, {'Category': ' Concept', 'Entity': 'UKâ€™s approach to SDR'}, {'Category': ' Report', 'Entity': 'Greening Finance: A Roadmap to Sustainable Investing'}, {'Category': ' Concept', 'Entity': 'Sendai Framework for Disaster Risk Reduction 2015â€“2030'}, {'Category': ' Concept', 'Entity': 'ESG information'}, {'Category': ' Date', 'Entity': datetime.datetime(2023, 10, 1, 0, 0)}, {'Category': ' Market', 'Entity': 'global financial markets'}, {'Category': ' Characteristic', 'Entity': 'international interoperability'}, {'Category': ' Concept', 'Entity': 'UKâ€™s approach to SDR'}, {'Category': ' Organization, Government Entity', 'Entity': 'UK Government'}, {'Category': ' Report', 'Entity': 'Greening Finance: A Roadmap to Sustainable Investing'}, {'Category': ' Concept', 'Entity': 'Sendai Framework for Disaster Risk Reduction 2015â€“2030'}, {'Category': ' Concept', 'Entity': 'holistic disaster risk management'}, {'Category': ' Concept', 'Entity': 'ESG information'}, {'Category': ' Concept', 'Entity': 'financial performance'}, {'Category': ' Concept', 'Entity': 'business valuation'}, {'Category': ' Group', 'Entity': 'private capital investors'}, {'Category': ' Organization, Group', 'Entity': 'companies'}, {'Category': ' Characteristic', 'Entity': 'quantitative'}, {'Category': ' Characteristic', 'Entity': 'self and externally regulated'}, {'Category': ' Characteristic', 'Entity': 'approvals'}, {'Category': ' Characteristic', 'Entity': 'industry-approved estimations'}, {'Category': ' Characteristic', 'Entity': 'data validation tools'}, {'Category': ' Characteristic', 'Entity': 'primary data'}, {'Category': ' Characteristic', 'Entity': 'Improved long-term financial performance'}, {'Category': ' Characteristic', 'Entity': 'Improved risk management'}, {'Category': ' Characteristic', 'Entity': 'Better alignment with personal values'}, {'Category': ' Concept', 'Entity': 'generate long-term financial returns'}, {'Category': ' Date', 'Entity': datetime.datetime(2023, 10, 1, 0, 0)}, {'Category': ' Organization', 'Entity': 'international monetary fund'}, {'Category': ' Market', 'Entity': 'global financial markets'}, {'Category': ' Event, Characteristic, Concept', 'Entity': 'transparency'}, {'Category': ' Characteristic', 'Entity': 'international interoperability'}, {'Category': ' Concept', 'Entity': 'UKâ€™s approach to SDR'}, {'Category': ' Concept', 'Entity': 'UKâ€™s approach to SDR'}, {'Category': ' Characteristic', 'Entity': 'international interoperability'}, {'Category': ' Organization, Government Entity', 'Entity': 'UK Government'}, {'Category': ' Concept', 'Entity': 'UK Green Taxonomy'}, {'Category': ' Concept', 'Entity': 'holistic nature risk management approach of the TNFD'}, {'Category': ' Action', 'Entity': 'Consultation on draft UK Sustainability Reporting Standards'}, {'Category': ' Action', 'Entity': 'Endorsement decision and publication of UK Sustainability Disclosure Standards'}, {'Category': ' Action', 'Entity': 'further consultation'}, {'Category': ' Action', 'Entity': 'mandatory disclosures'}, {'Category': ' Action', 'Entity': 'initial voluntary phase of reporting'}, {'Category': ' Action', 'Entity': 'consultation feedback'}, {'Category': ' Action', 'Entity': 'Parliamentary approval'}, {'Category': ' Report, Action', 'Entity': 'consultation'}, {'Category': ' Report', 'Entity': 'Greening Finance: A Roadmap to Sustainable Investing'}, {'Category': ' Concept, Report', 'Entity': 'framework document'}, {'Category': ' Activity', 'Entity': 'work'}, {'Category': ' Report', 'Entity': 'IFRS - IFRS Sustainability Standards Navigator'}, {'Category': ' Organization', 'Entity': 'UK Sustainability Disclosure Technical Advisory Committee'}, {'Category': ' Report', 'Entity': 'Mobilising Green Investment - 2023 Green Finance Strategy'}, {'Category': ' Concept, Report', 'Entity': 'framework document'}, {'Category': ' Characteristic', 'Entity': 'further detail about that process'}, {'Category': ' Action', 'Entity': 'International Sustainability Standards Board (ISSB) baseline standards'}, {'Category': ' Concept', 'Entity': 'Environment, Social and Governance disclosures'}, {'Category': ' Organization', 'Entity': 'IFRS'}, {'Category': ' Characteristic', 'Entity': 'further detail about that process'}, {'Category': ' Concept, Report', 'Entity': 'framework document'}, {'Category': ' Action', 'Entity': 'International Sustainability Standards Board (ISSB) baseline standards'}, {'Category': ' Organization', 'Entity': 'IFRS'}, {'Category': ' Action', 'Entity': 'International Sustainability Standards Board (ISSB) baseline standards'}, {'Category': ' Characteristic', 'Entity': 'further detail about that process'}, {'Category': ' Concept, Report', 'Entity': 'framework document'}, {'Category': ' Concept, Report', 'Entity': 'framework document'}, {'Category': ' Characteristic', 'Entity': 'further detail about that process'}, {'Category': ' Report', 'Entity': 'IFRS - IFRS Sustainability Standards Navigator'}, {'Category': ' Report', 'Entity': 'Mobilising Green Investment - 2023 Green Finance Strategy'}, {'Category': ' Report', 'Entity': 'Greening Finance: A Roadmap to Sustainable Investing'}, {'Category': ' Action', 'Entity': 'International Sustainability Standards Board (ISSB) baseline standards'}, {'Category': ' Organization', 'Entity': 'IFRS'}, {'Category': ' Action', 'Entity': 'Assessment concludes and recommendations provided'}, {'Category': ' Action', 'Entity': 'Assessment of IFRS S1 and IFRS S2'}, {'Category': ' Action', 'Entity': 'Consultation on draft UK Sustainability Reporting Standards'}, {'Category': ' Action', 'Entity': 'Endorsement decision and publication of UK Sustainability Disclosure Standards'}, {'Category': ' Activity', 'Entity': 'work'}, {'Category': ' Report', 'Entity': 'IFRS - IFRS Sustainability Standards Navigator'}, {'Category': ' Organization', 'Entity': 'UK Sustainability Disclosure Technical Advisory Committee'}, {'Category': ' Report', 'Entity': 'Mobilising Green Investment - 2023 Green Finance Strategy'}, {'Category': ' Activity', 'Entity': 'work'}, {'Category': ' Target', 'Entity': 'TARGET 1.2'}, {'Category': ' Report', 'Entity': 'IFRS - IFRS Sustainability Standards Navigator'}, {'Category': ' Organization', 'Entity': 'UK Sustainability Disclosure Technical Advisory Committee'}, {'Category': ' Action', 'Entity': 'Assessment concludes and recommendations provided'}, {'Category': ' Action', 'Entity': 'Assessment of IFRS S1 and IFRS S2'}, {'Category': ' Report', 'Entity': 'Mobilising Green Investment - 2023 Green Finance Strategy'}, {'Category': ' Action', 'Entity': 'make rules for overseas funds'}, {'Category': ' Policy, Action', 'Entity': 'Final anti-greenwashing guidance'}, {'Category': ' Characteristic', 'Entity': 'UK-endorsed standards'}, {'Category': ' Organization', 'Entity': 'Financial Conduct Authority (FCA)'}, {'Category': ' Concept, Policy', 'Entity': 'UK Sustainability Reporting Standards'}, {'Category': ' Characteristic', 'Entity': 'UK-endorsed standards'}, {'Category': ' Concept, Policy', 'Entity': 'UK Sustainability Reporting Standards'}, {'Category': ' Organization', 'Entity': 'Financial Conduct Authority (FCA)'}, {'Category': ' Report, Action', 'Entity': 'consultation'}, {'Category': ' Action', 'Entity': 'make rules for overseas funds'}, {'Category': ' Action', 'Entity': 'Consultation on extending the regime to portfolio managers and final rules'}, {'Category': ' Action', 'Entity': 'Consultation on strengthening transition plan disclosure expectations in line with TPT framework'}, {'Category': ' Policy, Action', 'Entity': 'Final anti-greenwashing guidance'}, {'Category': ' Action', 'Entity': 'Staggered implementation of final rules'}, {'Category': ' Concept, Policy', 'Entity': 'UK Sustainability Reporting Standards'}, {'Category': ' Characteristic', 'Entity': 'UK-endorsed standards'}, {'Category': ' Action', 'Entity': 'Parliamentary approval'}, {'Category': ' Report, Action', 'Entity': 'consultation'}, {'Category': ' Report', 'Entity': 'Disclosure Framework'}, {'Category': ' Characteristic', 'Entity': 'voluntary'}, {'Category': ' Action', 'Entity': 'Parliamentary approval'}, {'Category': ' Organization, Government Entity', 'Entity': 'UK Government'}, {'Category': ' Report, Action', 'Entity': 'consultation'}, {'Category': ' Organization', 'Entity': 'Financial Conduct Authority (FCA)'}, {'Category': ' Organization', 'Entity': 'Financial Conduct Authority (FCA)'}, {'Category': ' Report', 'Entity': 'Disclosure Framework'}, {'Category': ' Characteristic', 'Entity': 'voluntary'}, {'Category': ' Characteristic', 'Entity': 'voluntary'}, {'Category': ' Report', 'Entity': 'Disclosure Framework'}, {'Category': ' Action', 'Entity': 'Consultation on extending the regime to portfolio managers and final rules'}, {'Category': ' Action', 'Entity': 'Consultation on strengthening transition plan disclosure expectations in line with TPT framework'}, {'Category': ' Action', 'Entity': 'Staggered implementation of final rules'}, {'Category': ' Concept', 'Entity': 'UK Green Taxonomy'}, {'Category': ' Concept', 'Entity': 'UK Green Taxonomy'}, {'Category': ' Organization, Government Entity', 'Entity': 'UK Government'}, {'Category': ' Characteristic', 'Entity': 'use cases'}, {'Category': ' Characteristic', 'Entity': 'specific activity level criteria'}, {'Category': ' Characteristic', 'Entity': 'overarching framework'}, {'Category': ' Characteristic', 'Entity': 'use cases'}, {'Category': ' Action', 'Entity': 'further consultation'}, {'Category': ' Action', 'Entity': 'mandatory disclosures'}, {'Category': ' Characteristic', 'Entity': 'specific activity level criteria'}, {'Category': ' Characteristic', 'Entity': 'overarching framework'}, {'Category': ' Action', 'Entity': 'initial voluntary phase of reporting'}, {'Category': ' Action', 'Entity': 'consultation feedback'}, {'Category': ' Characteristic', 'Entity': 'use cases'}, {'Category': ' Concept', 'Entity': 'UK Green Taxonomy'}, {'Category': ' Action', 'Entity': 'further consultation'}, {'Category': ' Action', 'Entity': 'mandatory disclosures'}, {'Category': ' Characteristic', 'Entity': 'specific activity level criteria'}, {'Category': ' Characteristic', 'Entity': 'overarching framework'}, {'Category': ' Action', 'Entity': 'initial voluntary phase of reporting'}, {'Category': ' Action', 'Entity': 'consultation feedback'}, {'Category': ' Concept', 'Entity': 'holistic nature risk management approach of the TNFD'}, {'Category': ' Concept', 'Entity': 'holistic nature risk management approach of the TNFD'}, {'Category': ' Organization, Government Entity', 'Entity': 'UK Government'}, {'Category': ' Action', 'Entity': 'Assessment concludes and recommendations provided'}, {'Category': ' Action', 'Entity': 'Assessment of IFRS S1 and IFRS S2'}, {'Category': ' Action', 'Entity': 'Consultation on draft UK Sustainability Reporting Standards'}, {'Category': ' Action', 'Entity': 'Endorsement decision and publication of UK Sustainability Disclosure Standards'}, {'Category': ' Action', 'Entity': 'Assessment concludes and recommendations provided'}, {'Category': ' Organization', 'Entity': 'UK Sustainability Disclosure Technical Advisory Committee'}, {'Category': ' Action', 'Entity': 'Assessment of IFRS S1 and IFRS S2'}, {'Category': ' Action', 'Entity': 'Consultation on draft UK Sustainability Reporting Standards'}, {'Category': ' Action', 'Entity': 'Endorsement decision and publication of UK Sustainability Disclosure Standards'}, {'Category': ' Action', 'Entity': 'Consultation on extending the regime to portfolio managers and final rules'}, {'Category': ' Action', 'Entity': 'Consultation on strengthening transition plan disclosure expectations in line with TPT framework'}, {'Category': ' Policy, Action', 'Entity': 'Final anti-greenwashing guidance'}, {'Category': ' Action', 'Entity': 'Staggered implementation of final rules'}, {'Category': ' Action', 'Entity': 'Consultation on extending the regime to portfolio managers and final rules'}, {'Category': ' Action', 'Entity': 'Consultation on strengthening transition plan disclosure expectations in line with TPT framework'}, {'Category': ' Policy, Action', 'Entity': 'Final anti-greenwashing guidance'}, {'Category': ' Action', 'Entity': 'Staggered implementation of final rules'}, {'Category': ' Action', 'Entity': 'make rules for overseas funds'}, {'Category': ' Action', 'Entity': 'make rules for overseas funds'}]

TypeError: list indices must be integers or slices, not str

In [260]:
import pandas as pd
from scipy.spatial.distance import cosine

# 1. Prepare the Semantic Identity for Gold and AI
# We combine Entity and Category into a single concept string
gold['semantic_identity'] = (    "Entity: " + gold['Entity'].astype(str) +     " | Category: " + gold['Category'].astype(str))

data_p1['semantic_identity'] = (    "Entity: " + data_p1['Entity'].astype(str) +     " | Category: " + data_p1['Category'].astype(str))
data_neo4j['semantic_identity'] = (    "Entity: " + data_neo4j['Entity'].astype(str) +     " | Category: " + data_neo4j['Category'].astype(str))
# 2. Get Embeddings for both lists (Bulk call is more efficient)
gold_identities = gold['semantic_identity'].tolist()
ai_identities = data_neo4j['semantic_identity'].tolist()

# Get embeddings from your 'emb' model
gold_vecs = client.embeddings.create(model="text-embedding-3-small", input=gold_identities).data
ai_vecs = client.embeddings.create(model="text-embedding-3-small", input=ai_identities).data

# Extract actual vectors
gold_vectors = [v.embedding for v in gold_vecs]
ai_vectors = [v.embedding for v in ai_vecs]

# 3. Calculate "Semantic Proximity" for each AI result
def get_validation_score(ai_vec, gold_vectors):
    # Distance to the nearest human-verified concept
    distances = [cosine(ai_vec, g_vec) for g_vec in gold_vectors]
    return min(distances)

# Apply to your 246 extractions
data_neo4j['validation_distance'] = [get_validation_score(vec, gold_vectors) for vec in ai_vectors]

# 4. Resulting DataFrame (includes entity, sentence, and category)
# Higher distance = lower confidence in the Entity+Category pair
final_validation = data_neo4j[['Entity', 'Category', 'validation_distance']]
final_validation.to_excel("SDR_Full_Validation_n4j.xlsx", index=False)

In [231]:
gold.head()

,Source Sentence,Entity,Category,semantic_identity
0,1.11 Given the overlap between IFRS S2 and the...,IFRS S2,STANDARD,Entity: IFRS S2 | Category: STANDARD
1,1.11 Given the overlap between IFRS S2 and the...,TPT Disclosure Framework,FRAMEWORK,Entity: TPT Disclosure Framework | Category: F...
2,1.11 Given the overlap between IFRS S2 and the...,FCA,Organization,Entity: FCA | Category: Organization
3,1.11 Given the overlap between IFRS S2 and the...,UK-endorsed ISSB standards,STANDARD,Entity: UK-endorsed ISSB standards | Category:...
4,1.11 Given the overlap between IFRS S2 and the...,ISSB,Organization,Entity: ISSB | Category: Organization

In [232]:
judge_template = """
You are an expert in SDR (Sustainable Disclosure Requirements Document).

Entity: "{entity}"
Assigned Label: "{label}"

Task:
- Decide if the label correctly describes the entity.
- Return JSON with fields:
  {{
    "is_correct": true or false,
    "reasoning": "short explanation"
  }}
"""

In [233]:
def llm_judge(prompt, client):
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )
    
    return response.choices[0].message.content

In [274]:
import json
import pandas as pd

def call_llm_judge_on_results(df, gold_anchors, client):
    # 1. Create a list of the 43 manual labels to give the LLM context
    anchor_summary = gold_anchors[['Entity', 'Category']].to_dict('records')
    
    results = []

    for index, row in df.iterrows():
        # Construct the specific prompt for this row
        prompt = f"""
        You are an expert Ontology Auditor for UK Sustainability Disclosure Requirements (SDR).
        
        EXTRACTED ENTITY: "{row['Entity']}"
        PREDICTED CATEGORY: "{row['Category']}"
        
        VALIDATION ANCHORS (Reference Examples): {anchor_summary}
        
        TASK:
        1. Compare the extracted pair to the gold anchors.
        2. Is this a logically valid SDR entity and correctly categorized based on the context?
        
        RETURN JSON ONLY:
        {{
            "is_valid": true,
            "confidence": 0.95,
            "reasoning": "Explanation here"
        }}
        """
        
        # Call your existing llm_judge function
        raw_response = llm_judge(prompt, client)
        
        try:
            # Clean the response in case the LLM added markdown code blocks
            clean_json = raw_response.replace("```json", "").replace("```", "").strip()
            parsed = json.loads(clean_json)
            results.append(parsed)
        except Exception as e:
            results.append({"is_valid": None, "confidence": 0, "reasoning": f"Error: {str(e)}"})

    # 2. Add the results back to your DataFrame
    res_df = pd.DataFrame(results)
    final_df = pd.concat([df.reset_index(drop=True), res_df], axis=1)
    
    return final_df

# To execute:
# final_validated_df = call_llm_judge_on_results(data, gold, client)

In [272]:
gold.head()

,Source Sentence,Entity,Category,semantic_identity
0,1.11 Given the overlap between IFRS S2 and the...,IFRS S2,STANDARD,Entity: IFRS S2 | Category: STANDARD
1,1.11 Given the overlap between IFRS S2 and the...,TPT Disclosure Framework,FRAMEWORK,Entity: TPT Disclosure Framework | Category: F...
2,1.11 Given the overlap between IFRS S2 and the...,FCA,Organization,Entity: FCA | Category: Organization
3,1.11 Given the overlap between IFRS S2 and the...,UK-endorsed ISSB standards,STANDARD,Entity: UK-endorsed ISSB standards | Category:...
4,1.11 Given the overlap between IFRS S2 and the...,ISSB,Organization,Entity: ISSB | Category: Organization

In [275]:
final_validated_n4j = call_llm_judge_on_results(data_neo4j, gold, client)

In [276]:
final_validated_n4j.to_excel("SDR_LLMasajudge_Results_n4j.xlsx")

In [236]:
final_validated_df.to_excel("SDR_LLMasajudge_Results_P1.xlsx")

In [249]:
data_p2.columns

Index(['Sentence', 'Subject', 'Subject_Category', 'Predicate', 'Object',
       'Object_Category'],
      dtype='object')

In [250]:
###for triples
import pandas as pd
from scipy.spatial.distance import cosine

# 1. Create the Semantic Identity for the Triples
# Format: "Subject (Category) -> Predicate -> Object (Category)"
gold_triples['triple_identity'] = (
    "Subject: " + gold_triples['Subject'].astype(str) + " (" + gold_triples['Subject Category'].astype(str) + ") " +
    "| Predicate: " + gold_triples['Predicate'].astype(str) + 
    " | Object: " + gold_triples['Object'].astype(str) + " (" + gold_triples['Object Category'].astype(str) + ")"
)

data_p2['triple_identity'] = (
    "Subject: " + data_p2['Subject'].astype(str) + " (" + data_p2['Subject_Category'].astype(str) + ") " +
    "| Predicate: " + data_p2['Predicate'].astype(str) + 
    " | Object: " + data_p2['Object'].astype(str) + " (" + data_p2['Object_Category'].astype(str) + ")"
)

In [262]:
gold_triples['triple_identity'] = (
    "Subject: " + gold_triples['Subject'].astype(str) + "| Predicate: " + gold_triples['Predicate'].astype(str) +   " | Object: " + gold_triples['Object'].astype(str) 
)

In [263]:
data_neo4j_trip['triple_identity'] = (
    "Subject: " + data_neo4j_trip['Subject'].astype(str) +     "| Predicate: " + data_neo4j_trip['Predicate'].astype(str) + 
    " | Object: " + data_neo4j_trip['Object'].astype(str) )

In [264]:
# 2. Get Embeddings for Triple Identities
gold_triple_strings = gold_triples['triple_identity'].tolist()
ai_triple_strings = data_neo4j_trip['triple_identity'].tolist()

# Get embeddings
gold_triple_res = client.embeddings.create(model="text-embedding-3-small", input=gold_triple_strings).data
ai_triple_res = client.embeddings.create(model="text-embedding-3-small", input=ai_triple_strings).data

# Extract vectors
gold_triple_vectors = [v.embedding for v in gold_triple_res]
ai_triple_vectors = [v.embedding for v in ai_triple_res]

In [265]:
# 3. Calculate "Topological Proximity"
def get_triple_validation_score(ai_vec, gold_vectors):
    # Find the distance to the closest manual triple
    distances = [cosine(ai_vec, g_vec) for g_vec in gold_vectors]
    return min(distances)

# Apply to your Neo4j extractions
data_neo4j_trip['triple_validation_distance'] = [get_triple_validation_score(vec, gold_triple_vectors) for vec in ai_triple_vectors]

# 4. Export Final Evaluation
#final_triple_validation = data_p2[['Sentence', 'Subject', 'Predicate', 'Object', 'triple_validation_distance']]
final_triple_validation = data_neo4j_trip[['Subject', 'Predicate', 'Object', 'triple_validation_distance']]
final_triple_validation.to_excel("SDR_Triple_Validation_neo4jTrip.xlsx", index=False)

In [267]:
data_neo4j_trip.head()

,Subject,Predicate,Object,triple_identity,triple_validation_distance
0,Government,AIMS_TO_MAKE_AVAILABLE,UK-endorsed ISSB standards,Subject: Government| Predicate: AIMS_TO_MAKE_A...,0.494870
1,Government,ANNOUNCED_INTENTION,consult on whether to broaden the scope of SDR...,Subject: Government| Predicate: ANNOUNCED_INTE...,0.220101
2,UK Sustainability Reporting Standards,APPLIES_TO,UK companies that do not fall within the FCAâ€...,Subject: UK Sustainability Reporting Standards...,0.443176
3,investment labels regime for funds based in th...,APPLIES_TO,funds based in the UK,Subject: investment labels regime for funds ba...,0.244124
4,anti-greenwashing rule,APPLIES_TO,FCA-authorised firms,Subject: anti-greenwashing rule| Predicate: AP...,0.248306

In [268]:
##llm-as-a-judge for triples
import json
import pandas as pd

def call_llm_judge_on_triples(df_ai_triples, df_gold_triples, client):
    # 1. Prepare the Relationship Gold Set for the LLM context
    # We provide the Judge with your 17 human-verified triples as reference
    anchor_summary = df_gold_triples[['Subject', 'Predicate', 'Object']].to_dict('records')
    
    results = []

    for index, row in df_ai_triples.iterrows():
        # Construct the specific prompt for Triple Validation
        prompt = f"""
        You are an expert Knowledge Graph Auditor for the UK Sustainability Disclosure Requirements (SDR).     
        AI-EXTRACTED TRIPLE:
        - Subject: "{row['Subject']}" 
        - Predicate: "{row['Predicate']}"
        - Object: "{row['Object']}" 
        
        GOLD STANDARD EXAMPLES (For Reference): {anchor_summary}
        
        TASK:
        1. Evaluate if the AI-extracted triple accurately represents the relationship described in the CONTEXT SENTENCE.
        2. Verify if the Categories (Subject_Category and Object_Category) are ontologically correct.
        3. Even if the Predicate is not identical to the Gold Standard, is it semantically equivalent and factually true?
        
        RETURN JSON ONLY:
        {{
            "is_valid": true/false,
            "confidence": 0.0-1.0,
            "reasoning": "Brief explanation of why this relationship is valid or a hallucination."
        }}
        """
        
        # Call your existing llm_judge function
        raw_response = llm_judge(prompt, client)
        
        try:
            # Clean and parse JSON
            clean_json = raw_response.replace("```json", "").replace("```", "").strip()
            parsed = json.loads(clean_json)
            results.append(parsed)
        except Exception as e:
            results.append({"is_valid": None, "confidence": 0, "reasoning": f"Error: {str(e)}"})

    # 2. Merge results with the original triple DataFrame
    res_df = pd.DataFrame(results)
    final_df = pd.concat([df_ai_triples.reset_index(drop=True), res_df], axis=1)
    
    return final_df

In [ ]:
# this one has sentences I don't include them for neo4j this belos query is valid for P2
##llm-as-a-judge for triples
#def call_llm_judge_on_triples(df_ai_triples, df_gold_triples, client):
#    # 1. Prepare the Relationship Gold Set for the LLM context
#    # We provide the Judge with your 17 human-verified triples as reference
#    anchor_summary = df_gold_triples[['Subject', 'Predicate', 'Object']].to_dict('records')
#    
#    results = []
#
#    for index, row in df_ai_triples.iterrows():
#        # Construct the specific prompt for Triple Validation
#        prompt = f"""
#        You are an expert Knowledge Graph Auditor for the UK Sustainability Disclosure Requirements (SDR).
#        
#        CONTEXT SENTENCE: "{row['Sentence']}"
#        
#        AI-EXTRACTED TRIPLE:
#        - Subject: "{row['Subject']}" ({row['Subject_Category']})
#        - Predicate: "{row['Predicate']}"
#        - Object: "{row['Object']}" ({row['Object_Category']})
#        
#        GOLD STANDARD EXAMPLES (For Reference): {anchor_summary}
#        
#        TASK:
#        1. Evaluate if the AI-extracted triple accurately represents the relationship described in the CONTEXT SENTENCE.
#        2. Verify if the Categories (Subject_Category and Object_Category) are ontologically correct.
#        3. Even if the Predicate is not identical to the Gold Standard, is it semantically equivalent and factually true?
#        
#        RETURN JSON ONLY:
#        {{
#            "is_valid": true/false,
#            "confidence": 0.0-1.0,
#            "reasoning": "Brief explanation of why this relationship is valid or a hallucination."
#        }}
#        """
#        
#        # Call your existing llm_judge function
#        raw_response = llm_judge(prompt, client)
#        
#        try:
#            # Clean and parse JSON
#            clean_json = raw_response.replace("```json", "").replace("```", "").strip()
#            parsed = json.loads(clean_json)
#            results.append(parsed)
#        except Exception as e:
#            results.append({"is_valid": None, "confidence": 0, "reasoning": f"Error: {str(e)}"})
#
#    # 2. Merge results with the original triple DataFrame
#    res_df = pd.DataFrame(results)
#    final_df = pd.concat([df_ai_triples.reset_index(drop=True), res_df], axis=1)
#    
#    return final_df

In [254]:
final_triples_audit = call_llm_judge_on_triples(data_p2, gold_triples, client)
final_triples_audit

,Sentence,Subject,Subject_Category,Predicate,Object,Object_Category,triple_identity,triple_validation_distance,is_valid,confidence,reasoning
0,sustainability disclosurerequirements: impleme...,UK Government,Organization,set out,2023 Green Finance Strategy,Document,Subject: UK Government (Organization) | Predic...,0.344288,True,0.9,The AI-extracted triple accurately captures th...
1,sustainability disclosurerequirements: impleme...,2023 Green Finance Strategy,Document,ensure,investors and consumers,Organization,Subject: 2023 Green Finance Strategy (Document...,0.330054,False,0.6,The AI-extracted triple inaccurately represent...
2,sustainability disclosurerequirements: impleme...,investors and consumers,Organization,can access,information,Concept,Subject: investors and consumers (Organization...,0.536332,False,0.7,The AI-extracted triple inaccurately identifie...
3,sustainability disclosurerequirements: impleme...,information,Concept,to inform,capital allocation,Process,Subject: information (Concept) | Predicate: to...,0.470465,False,0.7,The AI-extracted triple does not accurately re...
4,sustainability disclosurerequirements: impleme...,sustainability disclosure requirements (SDR),Concept,is,a framework,Concept,Subject: sustainability disclosure requirement...,0.399153,True,0.9,The AI-extracted triple accurately captures th...
...,...,...,...,...,...,...,...,...,...,...,...
205,"to view this licence, visitnationalarchives.go...",this licence,Document,view,nationalarchives.gov.uk/doc/open-government-li...,Document,Subject: this licence (Document) | Predicate: ...,0.541277,False,0.4,The AI-extracted triple inaccurately represent...
206,where we have identified any third party copyr...,third party copyright information,Concept,identified,copyright holders,Organization,Subject: third party copyright information (Co...,0.534748,False,0.4,The AI-extracted triple does not accurately re...
207,where we have identified any third party copyr...,you,Organization,need to obtain permission from,copyright holders,Organization,Subject: you (Organization) | Predicate: need ...,0.535200,False,0.6,The AI-extracted triple misrepresents the rela...
208,this publication is available at: www.gov.uk/o...,this publication,Document,is available at,www.gov.uk/official-documents,Concept,Subject: this publication (Document) | Predica...,0.537520,True,0.9,The AI-extracted triple accurately represents ...
209,any enquiries regarding this publication shoul...,this publication,Document,should be sent to,us,Organization,Subject: this publication (Document) | Predica...,0.523939,False,0.7,The AI-extracted triple inaccurately represent...

In [255]:
final_triples_audit.to_excel("SDR_LLMasajudge_p2.xlsx")

In [269]:
final_triples_audit_n4jt = call_llm_judge_on_triples(data_neo4j_trip, gold_triples, client)
final_triples_audit_n4jt

,Subject,Predicate,Object,triple_identity,triple_validation_distance,is_valid,confidence,reasoning
0,Government,AIMS_TO_MAKE_AVAILABLE,UK-endorsed ISSB standards,Subject: Government| Predicate: AIMS_TO_MAKE_A...,0.494870,True,0.9,The AI-extracted triple accurately represents ...
1,Government,ANNOUNCED_INTENTION,consult on whether to broaden the scope of SDR...,Subject: Government| Predicate: ANNOUNCED_INTE...,0.220101,True,0.9,The AI-extracted triple accurately represents ...
2,UK Sustainability Reporting Standards,APPLIES_TO,UK companies that do not fall within the FCAâ€...,Subject: UK Sustainability Reporting Standards...,0.443176,True,0.9,The AI-extracted triple accurately represents ...
3,investment labels regime for funds based in th...,APPLIES_TO,funds based in the UK,Subject: investment labels regime for funds ba...,0.244124,True,0.9,The AI-extracted triple accurately represents ...
4,anti-greenwashing rule,APPLIES_TO,FCA-authorised firms,Subject: anti-greenwashing rule| Predicate: AP...,0.248306,True,0.9,The AI-extracted triple accurately represents ...
...,...,...,...,...,...,...,...,...
116,Government,WELCOMES,Taskforce on Nature-related Financial,Subject: Government| Predicate: WELCOMES | Obj...,0.470758,True,0.9,The AI-extracted triple accurately represents ...
117,Government,WELCOMES_COMMITMENT,ISSB,Subject: Government| Predicate: WELCOMES_COMMI...,0.557051,True,0.9,The AI-extracted triple accurately represents ...
118,UK Government,WILL_CONSULT_ON,disclosure requirements against the UK Sustain...,Subject: UK Government| Predicate: WILL_CONSUL...,0.335150,True,0.9,The AI-extracted triple accurately represents ...
119,Government,WILL_CONSULT_ON,how the UKâ€™s largest companies can disclose ...,Subject: Government| Predicate: WILL_CONSULT_O...,0.223054,True,0.9,The AI-extracted triple accurately reflects th...
120,FCA,WILL_CONSULT_ON,updating TCFD-aligned rules to UK Sustainabili...,Subject: FCA| Predicate: WILL_CONSULT_ON | Obj...,0.289389,True,0.9,The AI-extracted triple accurately represents ...

In [270]:
final_triples_audit_n4jt.to_excel("SDR_LLMasajudge_neo4jTrip.xlsx")

In [171]:
import pandas as pd

# Step A: Get the list of entity strings for the embedding model
entities_list = df['Entity'].astype(str).tolist()

# Step B: Get Embeddings (using the same 'emb' logic from your notebook)
# This creates vectors for all 246 (or more) entities at once
embedding_response = client.embeddings.create(
    model="text-embedding-3-small",
    input=entities_list
)

# Step C: Combine everything back into a DataFrame
# We keep 'entity' and 'sentence' as required for your Knowledge Graph
records = []
for i, row in enumerate(df.to_dict('records')):
    records.append({
        'entity': row['Entity'],
        'category': row['Category'],
        'sentence': row['Sentence'],
        'embedding': embedding_response.data[i].embedding
    })

df_vectorized = pd.DataFrame(records)

In [172]:
df_vectorized

,entity,category,sentence,embedding
0,Sustainability Disclosure Requirements,N/A,sustainability disclosurerequirements: impleme...,"[0.005727109964936972, 0.020185058936476707, 0..."
1,Implementation Update 2024,N/A,sustainability disclosurerequirements: impleme...,"[-0.016069985926151276, -0.04543142393231392, ..."
2,2023 Green Finance Strategy,N/A,sustainability disclosurerequirements: impleme...,"[-0.007716048043221235, 0.010138679295778275, ..."
3,UK Government,N/A,sustainability disclosurerequirements: impleme...,"[-0.010704738087952137, 0.01040758565068245, 0..."
4,Green Investment,N/A,sustainability disclosurerequirements: impleme...,"[-0.007596506271511316, 0.03976994380354881, 0..."
...,...,...,...,...
147,N/A,N/A,where we have identified any third party copyr...,"[-0.00831184908747673, -0.0018222130602225661,..."
148,N/A,N/A,where we have identified any third party copyr...,"[-0.00831184908747673, -0.0018222130602225661,..."
149,N/A,N/A,this publication is available at: www.gov.uk/o...,"[-0.00831184908747673, -0.0018222130602225661,..."
150,N/A,N/A,this publication is available at: www.gov.uk/o...,"[-0.00831184908747673, -0.0018222130602225661,..."
151,Raw Response,Error,any enquiries regarding this publication shoul...,"[-0.007471879944205284, 0.04602368175983429, -..."